version: 2
commands:
  - command: notepad
    arguments:
      - ${INPUT}
    title: メモ帳

# tools setting
tools:
  cppcheck: &cppcheck
    lint-command: 'cppcheck --enable=style --error-exitcode=1 ${INPUT}'
    lint-stdin: false
    lint-formats:
      - '%f:%l:%c: %m'

  vale: &vale
    lint-command: 'vale --relative --output line ${INPUT}'
    lint-stdin: false
    lint-ignore-exit-code: true
    lint-formats:
      - '%f:%l:%c:%*[^:]:%m'

  proselint: &proselint
    lint-command: 'proselint ${INPUT}'
    lint-stdin: false
    lint-ignore-exit-code: true
    lint-formats:
      - '%f:%l:%c:%m'

  writegood: &writegood
    lint-command: 'writegood --parse ${INPUT}'
    lint-stdin: false
    lint-ignore-exit-code: true
    lint-formats:
      - '%f:%l:%c:%m'

  vint: &vint
    lint-command: 'vint -'
    lint-stdin: true

  markdownlint: &markdownlint
    lint-command: 'markdownlint -s'
    lint-stdin: true
    lint-formats:
      - '%f:%l %m'

  jq: &jq
    format-command: 'jq .'
    lint-stdin: true
    lint-ignore-exit-code: true

  shellcheck: &shellcheck
    lint-command: 'shellcheck -s sh -f gcc -x -o all -'
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %trror: %m'
      - '%f:%l:%c: %tarning: %m'
      - '%f:%l:%c: %tote: %m'

# languages setting
languages:
  vim:
    <<: *vint

  markdown:
    <<: *proselint
    <<: *writegood

  json:
    <<: *jq

  text:
    <<: *writegood

  mail:
    <<: *proselint
    <<: *writegood

  cpp:
    <<: *cppcheck

  c:
    <<: *cppcheck

  sh:
    <<: *shellcheck
